"""add day9 signature metadata

Revision ID: 7c68a9156627
Revises: ef96aec5c521
Create Date: 2026-08-16 23:15:05.440317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c68a9156627'
down_revision: Union[str, Sequence[str], None] = 'ef96aec5c521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('nonce', sa.LargeBinary(), nullable=False))
    op.alter_column('document_versions', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('encryption_keys', sa.Column('document_version_id', sa.UUID(), nullable=False))
    op.add_column('encryption_keys', sa.Column('wrapped_key', sa.LargeBinary(), nullable=False))
    op.add_column('encryption_keys', sa.Column('key_version', sa.String(), nullable=False))
    op.drop_constraint(op.f('encryption_keys_organization_id_fkey'), 'encryption_keys', type_='foreignkey')
    op.create_foreign_key(None, 'encryption_keys', 'document_versions', ['document_version_id'], ['id'])
    op.drop_column('encryption_keys', 'organization_id')
    op.drop_column('encryption_keys', 'encrypted_key')
    op.drop_column('encryption_keys', 'algorithm')
    op.drop_column('encryption_keys', 'key_name')
    op.add_column('signatures', sa.Column('hash_at_signing', sa.String(length=64), nullable=False))
    op.add_column('signatures', sa.Column('public_key', sa.Text(), nullable=False))
    op.alter_column('signatures', 'document_version_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('signatures', 'signer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('signatures', 'signature',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('signatures', 'algorithm',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signatures', 'algorithm',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('signatures', 'signature',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('signatures', 'signer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('signatures', 'document_version_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('signatures', 'public_key')
    op.drop_column('signatures', 'hash_at_signing')
    op.add_column('encryption_keys', sa.Column('key_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('encryption_keys', sa.Column('algorithm', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('encryption_keys', sa.Column('encrypted_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('encryption_keys', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'encryption_keys', type_='foreignkey')
    op.create_foreign_key(op.f('encryption_keys_organization_id_fkey'), 'encryption_keys', 'organizations', ['organization_id'], ['id'])
    op.drop_column('encryption_keys', 'key_version')
    op.drop_column('encryption_keys', 'wrapped_key')
    op.drop_column('encryption_keys', 'document_version_id')
    op.alter_column('document_versions', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('document_versions', 'nonce')
    # ### end Alembic commands ###
