"""add document shares

Revision ID: ee2688c6a568
Revises: 7c68a9156627
Create Date: 2026-08-17 15:18:26.732190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee2688c6a568'
down_revision: Union[str, Sequence[str], None] = '7c68a9156627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('encryption_keys', 'document_version_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('encryption_keys', 'wrapped_key',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('encryption_keys', 'key_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('signatures', 'hash_at_signing',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('signatures', 'public_key',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signatures', 'public_key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('signatures', 'hash_at_signing',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('encryption_keys', 'key_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('encryption_keys', 'wrapped_key',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('encryption_keys', 'document_version_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
